[package]
name = "solana-wallet-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = "1.0.219"
solana-account = "2.1.20"
solana-client = "2.1.20"
solana-sdk = "2.1.20"
tokio = "1.45.1"
